# $$ Quantum \space Computing $$

***Quantum computin***g uses specialized technology—including computer hardware and algorithms that take advantage of quantum mechanics—to solve complex problems that classical computers or supercomputers can’t solve, or can’t solve quickly enough.

It uses quantum bits, or **qubits**, A qubit is a two-state quantum-mechanical system.
- A two-state quantum system, also known as a two-level system, is a fundamental concept in quantum mechanics. It refers to a system that can exist in exactly two distinct quantum states at any given time.
- A qubit can exist in a superposition of its two “basis” states, unlike a classical bit that can only represent either zero or one.
- Qubits can represent any combination of both zero and one simultaneously, creating complex, multidimensional computational spaces.


---

In [2]:
import numpy as np
import math

In [3]:
from qiskit.circuit.library import (
                                XGate, ZGate, YGate, HGate,
                                RXGate, RYGate, RZGate
                                    )
from qiskit.visualization import array_to_latex

## Basics

A pure qubit state is a coherent superposition of the basis states. This means that a single qubit (
${ \psi }$) can be described by a linear combination of ${ |0\rangle }$ and ${ |1\rangle }$:

$${ |\psi \rangle =\alpha |0\rangle +\beta |1\rangle } = 
    \begin{bmatrix} 
    \alpha \\
    \beta
    \end{bmatrix}$$
where α and β are the probability amplitudes, and are both complex numbers. When we measure this qubit in the standard basis, according to the Born rule, the probability of outcome 
${ |0\rangle }$ with value "0" is ${ |\alpha |^{2}}$ and the probability of outcome ${ |1\rangle }$ with value "1" is 
${ |\beta |^{2}}$. Because the **absolute squares of the amplitudes equate to probabilities**, it follows that 
${ \alpha }$ and ${ \beta }$ must be constrained according to the **$Normalization \space Equation:$**
$${ |\alpha |^{2}+|\beta |^{2}=1.}$$

In [45]:
zero_vector = np.array([[1], [0]])
print(zero_vector.shape)
array_to_latex(zero_vector, prefix=r'Ground \space State = Zero \space Vector = |0\rangle= ')

(2, 1)


<IPython.core.display.Latex object>

In [47]:
one_vector = np.array([0, 1]).reshape(2, 1)
array_to_latex(one_vector, prefix=r'Excited \space State = One \space Vector = |1\rangle= ')

<IPython.core.display.Latex object>

### Dirac Notation (Bra-Ket Notation) [More](https://www.mathsisfun.com/physics/bra-ket-notation.html)
- Notation for linear algebraa and linear operators on complex vector spaces in both finite and infinite dimentins.
- Notaiont to refere to a vector with complex elements with any number of dimentions.

ket is defined as $|x \rangle$

In [6]:
array_to_latex(one_vector, prefix=r'|1\rangle = ')

<IPython.core.display.Latex object>

Bra is defined as $\langle x|$

In [7]:
array_to_latex(one_vector.conj().T, prefix=r'\langle1| = ')

<IPython.core.display.Latex object>

Inner Product(Dot) is defined as $\langle \psi_1| \psi_2 \rangle$
- Represent the similarity between $|\psi_1\rangle , |\psi_2\rangle$
- ${\langle \psi |\psi \rangle = 1}$, or equivalently ${ {\big \|}|\psi \rangle {\big \|}^{2}=1}$
- dot(x.conj().T, y) == vdot(x, y)

In [8]:
np.dot(zero_vector.conj().T, one_vector)

array([[0]])

In [9]:
np.vdot(zero_vector, one_vector)

0

Cross Product is defined as $|\psi_1\rangle\langle\psi_2|$
- Represent (Matrix - Operator - Gate)
- called Diagonal Representation | Spectrol Decomposition

In [10]:
outer = np.dot(zero_vector, one_vector.conj().T)
array_to_latex(outer, prefix=r'|0\rangle\langle1| = ')

<IPython.core.display.Latex object>

In [11]:
outer_not = np.dot(zero_vector, one_vector.conj().T) + np.dot(one_vector, zero_vector.conj().T)
array_to_latex(outer_not, prefix=r'I = |0\rangle\langle1| + |1\rangle\langle0| = ')

<IPython.core.display.Latex object>

## Quantum Gates
 Quantum gate (matrix or operator) is a basic quantum circuit operating on a small number of qubits. Quantum logic gates are the building blocks of quantum circuits, like classical logic gates are for conventional digital circuits.

 * Unlike many classical logic gates, quantum logic gates are **`reversible`**. It is possible to perform classical computing using only reversible gates.

 * Quantum gates are `unitary` operators.

 * The action of the gate on a specific quantum state is found by multiplying the vector $|\psi _{1}\rangle$, which represents the state by the matrix $U$ representing the gate. The result is a new quantum state $|\psi _{2}\rangle$:

$${ U|\psi _{1}\rangle =|\psi _{2}\rangle .}$$
 

### Pauli gates (X,Y,Z)
-  The three Pauli matrices ${ (\sigma _{x},\sigma _{y},\sigma _{z})}$ act on a single qubit.
- The Pauli matrices are **involutory**, meaning that the square of a Pauli matrix is the identity matrix.
$${ I^{2}=X^{2}=Y^{2}=Z^{2}=-iXYZ=I}$$

$$X-Gate$$
- Equivelent to NOT gate in classical computers.
- Flips Qubit $\pi$ radians around X-axis.
- Sometimes called **Bit-Flip**.

In [70]:
x_gate = XGate().to_matrix()
array_to_latex(x_gate, prefix='X = \sigma_x = \operatorname {NOT} =')

<IPython.core.display.Latex object>

In [66]:
not0 = x_gate @ zero_vector
array_to_latex(not0, prefix='X |0\\rangle = |1\\rangle = ')

<IPython.core.display.Latex object>

In [61]:
not1 = x_gate @ one_vector
array_to_latex(not1, prefix='X |1\\rangle = |0\\rangle = ')

<IPython.core.display.Latex object>

- Performs probability swaping.

In [56]:
vec = [[.43], [.57]]
array_to_latex(vec, prefix='|vec\\rangle = ')

<IPython.core.display.Latex object>

In [57]:
vec_x = x_gate @ vec
array_to_latex(vec_x, prefix='X |vec\\rangle =')

<IPython.core.display.Latex object>

$$Y-Gate$$
- Flips Qubit $\pi$ randians around Y-axis.

In [67]:
y_gate = YGate().to_matrix()
array_to_latex(y_gate, prefix="Y = \sigma_y = ")

<IPython.core.display.Latex object>

$$Z-Gate$$
- Flips Qubit $\pi$ randians around Z-axis.
- Sometimes called **Phase-Flip**.

In [68]:
z_gate = ZGate().to_matrix()
array_to_latex(z_gate, prefix='Z = \sigma_z =')

<IPython.core.display.Latex object>

### Hadmard Gate
$$H-Gate$$

The Hadamard or Walsh-Hadamard gate, acts on a single qubit. It maps the basis states 
$${\textstyle |0\rangle \mapsto {\frac {|0\rangle +|1\rangle }{\sqrt {2}}}} \space\space and \space\space
 {\textstyle |1\rangle \mapsto {\frac {|0\rangle -|1\rangle }{\sqrt {2}}}}$$ 


(it creates an `equal` superposition state if given a computational basis state). 

The two states 
${ (|0\rangle +|1\rangle )/{\sqrt {2}}}$ and ${ (|0\rangle -|1\rangle )/{\sqrt {2}}}$ are sometimes written 
${ |+\rangle }$ and ${ |-\rangle }$ respectively. 

The Hadamard gate performs a rotation of 
${ \pi }$ about the axis ${ ({\hat {x}}+{\hat {z}})/{\sqrt {2}}}$ at the Bloch sphere, and is therefore **`involutory`**. 


Circuit representation of Hadamard gate ${ H={\frac {1}{\sqrt {2}}}{\begin{bmatrix}1&1\\1&-1\end{bmatrix}}.}$

- Can produce **true random numbers** as it outputs $|1\rangle, |0\rangle$ with probability `50%` each.
- Used in Quantum Random Number Generator `QRNG`, which usally used in security.

In [73]:
h_gate = HGate().to_matrix()
array_to_latex(h_gate, prefix='H = ')

<IPython.core.display.Latex object>

### What is the difference between a unitary matrix and a hermitian matrix?

- Unitary Matrix (U): 
    - square matrix, where the conjugate transpose of a matrix is equal to its inverse. $U^H = U^{\dagger}= U^{-1}$ $$U^\dagger U = I$$


In [16]:
np.allclose(np.dot(x_gate, x_gate.conj().T), np.identity(2))

True

In [17]:
np.allclose(x_gate, np.linalg.inv(x_gate))

True

- Hermition Matrix (H):
    - Square matrix, where the conjugate transpose of a matrix is equal to the original. $H^H = H^{\dagger}= H$
    - Has real eigenvalues.
    - Has orthogonal eigenvectors (if the eigenvalues are different).
    - The set of eignevectors of hermition operator can be used as basis. (Spectral Theorm)

In [18]:
np.allclose(x_gate, x_gate.conj().T)

True

In [19]:
np.allclose(z_gate, z_gate.conj().T)

True

Eigenvalues of a hermition matrix (operator) (gate) represent the energy of the system in respect to the operator.

In [20]:
np.linalg.eigvals(z_gate).real

array([ 1., -1.])

- The maximum energy for ZGate is `1`.
- The minimum energy for ZGate is `-1`.

---

## Measurement

In [21]:
psi = x_gate @ zero_vector
array_to_latex(psi)

<IPython.core.display.Latex object>

In [22]:
hpsi  = h_gate @ zero_vector
array_to_latex(hpsi)

<IPython.core.display.Latex object>

The expectation value of an observable (hermitian operator, hamiltonian) in this case it's $\hat{o}$ is defined as: $\langle 1| \hat{o} |1\rangle$
- represent the energy of the system in respect to the operator $\hat{o}$
- Projection of the vector to the axis of the operator.

In [23]:
#### psi(one_vev) is aligned with the negative part of the z-axis. cos(180) = -1
(psi.conj().T @ z_gate @ psi).real

array([[-1.]])

In [24]:
#### hpsi is orthogonal on the z-axis so the projection will be zero. cos(90) = 0
(hpsi.conj().T @ z_gate @ hpsi).real

array([[0.]])

In [25]:
#### zero_vec is aligned with the z-axis. cos(0) = 1
(zero_vector.conj().T @ z_gate @ zero_vector).real

array([[1.]])

In [26]:
#### zero_vec is orthogonal on the x-axis so the projection will be zero. cos(90) = 0
(zero_vector.conj().T @ x_gate @ zero_vector).real

array([[0.]])

In [27]:
#### hpsi is aligned on the x-axis so the projection will be one. cos(0) = 1
(hpsi.conj().T @ x_gate @ hpsi).real

array([[1.]])

In [28]:
#### one_vec is orthogonal on the x-axis so the projection will be zero. cos(90) = 0
(one_vector.conj().T @ x_gate @ one_vector).real

array([[0.]])

In [29]:
#### one_vec is orthogonal on the y-axis so the projection will be zero. cos(90) = 0
(one_vector.conj().T @ y_gate @ one_vector).real

array([[0.]])

##### Q. How can you measure the zero_vector defined in this notebook on the x-basis while avoiding getting zeros all the time?

No, We can't because zero_vec is orthogonal on the x-axis so the projection will be zero. cos(90) = 0



## Encode and Measure the same datapoint

In [30]:
num = .5
rx_gate = RXGate(num).to_matrix()
# rx_gate = RXGate(np.pi / 8).to_matrix()
# array_to_latex(rx_gate)
encoded = rx_gate @ zero_vector
array_to_latex(encoded)

<IPython.core.display.Latex object>

In [31]:
measured = (encoded.conj().T @ z_gate @ encoded).real

In [32]:
ret = math.acos(measured)

In [33]:
np.allclose(num, ret)

True

In [34]:
# hamiltonian or Observable
z_gate = ZGate().to_matrix()
y_gate = YGate().to_matrix()
x_gate = XGate().to_matrix()

z_gate.shape

(2, 2)

---
$$ Good \space Luck ✨$$ 